#!/usr/bin/env bash

usage() 
{
cat <<EOT
    Bash dotfiles - ZiYang 
    Usage: $(basename "$0") [options]
    Options:
        -h , --help     print help 
EOT
}

signal_exit()
{
    echo "\n Ctrl + c.\n"
    exit 0
}

trap "signal_exit" TERM INT HUP
